### PR TITLE
Adding vue-style-loader

### PR DESCRIPTION
**Pull request by darenju**
Fresh install throws error on `npm run dev`:

```
ERROR in ./src/App.vue
Module not found: Error: Cannot resolve module 'vue-style-loader'
```

### CODE REVIEW

**Comment by craigatk** [comment]
I hit this same error as well - thanks for fixing it!

**Comment by tkdave** [comment]
Resolves Issue #288.

**Comment by chrisvfritz** [comment]
@zigomir can take a look at this later, as he knows more about the reasons for removal, but I'll just merge this for now.

**Comment by darenju** [comment]
Thanks for merging. I'd be interested in knowing the reasons as well.

**Pull request merged**
