### PR TITLE
Add scope hoisting in the prod config

### PR DESCRIPTION
**Pull request by agnivade**
https://medium.com/webpack/brief-introduction-to-scope-hoisting-in-webpack-8435084c171f

### CODE REVIEW

**Comment by LinusBorg** [comment]
I'm not sure if we can consider this plugin production-ready yet. Last time I checked this was still in the early stages, but admittedly that was some time ago.

**Comment by agnivade** [comment]
Scope hoisting came with webpack 3 which was released in June 19. The template uses 3.6 now. A lot of companies including mine have successfully used scope hoisting now. It was even featured in the Chrome Dev Summit video by @addyosmani.

**Comment by kuoruan** [comment]
@agnivade Enable this gives me a Error
```
Uncaught TypeError: Cannot read property 'call' of undefined
    at r (manifest.3fe6de900fd915a3ce9a.js:1)
    at Object.NHnr (app.3cf392e250a975da6f37.js:1)
    at r (manifest.3fe6de900fd915a3ce9a.js:1)
    at window.webpackJsonp (manifest.3fe6de900fd915a3ce9a.js:1)
    at app.3cf392e250a975da6f37.js:1
```
My webpack version is 3.8.1

**Comment by agnivade** [comment]
Well, I guess you should raise an issue in the webpack repo. I just sent this PR because I applied this and noticed good improvements. I am no way an expert in Webpack.

**Comment by kuoruan** [comment]
@agnivade OK, thank you. I find the same issue at https://github.com/webpack/webpack/issues/959#issuecomment-310299833

**Pull request merged**
