### PR TITLE
autoprefixer for external CSS

### PR DESCRIPTION
**Pull request by Grafikart**
Fix feature request #85

Here is a summary : 

- Removed autoprefixer from vue
- Added postCSS loader
- Added postcss autoprefixer
- Added a new configuration setting to define browser support
- Added postcss mqpacker to merge media query

### CODE REVIEW

**Comment by shentao** [comment]
@Grafikart Thanks a lot! 🍺

**Comment by chrisvfritz** [comment]
This seems to work. @yyx990803 Does this look like it'll play well with `vue-loader`?

**Comment by yyx990803** [comment]
`vue-loader` still uses postcss internally (when using scoped styles), so I think this would cause postcss to be run twice on Vue component CSS in some cases.

What I think would be more ideal:

1. Only chain `postcss-loader` for non-Vue CSS (probably by adding an option to the `cssLoaders` function)
2. Disable autoprefixer in Vue config, and let both `vue-loader` and `postcss-loader` share the same Array of postcss plugins.

**Comment by Grafikart** [comment]
Ok I see what you mean, I'll try to implement your idea

**Comment by hekigan** [comment]
Hi guys,

I think that this is good stuff, but I am concern with adding ```mqpacker``` to the build process for the following reason:
https://github.com/hail2u/node-css-mqpacker/issues/16

**Comment by Grafikart** [comment]
I got your concern @hekigan, this plugin can be removed if needed after the template is installed so I don't think it's a big deal (but if it's blocking I can remove it)

**Comment by Grafikart** [comment]
@hekigan I removed mqpacker since it was only merging mediaquery from the same file (so it was quite useless to add it :( )

**Comment by Grafikart** [comment]
@yyx990803 I just did the changes you requested

**Comment by yyx990803** [comment]
@Grafikart thanks!
@chrisvfritz would appreciate you taking a look at this

**Comment by chrisvfritz** [comment]
This looks really great. I just submitted [a PR to your PR](https://github.com/Grafikart/webpack/pull/1) 😜 with a slight refactor. I changed the strategy used a little bit, so am happy to hear your thoughts on that. Afterwards, it should be good to merge. 😄

**Comment by Grafikart** [comment]
I'm now wondering if all this work worth it. I mean webpack is not designed for CSS and I think we could achieve the same result doing postcss transform when webpack extract text plugin finish. 

We build => webpack generate assets => postcss is used on compiled CSS (remove duplicates, autoprefix, mergemediaqueries...)

This design could make things simpler.

**Pull request closed without merging**
