### PR TITLE
Fixed Hello component file path and reordered it to the top

### PR DESCRIPTION
**Pull request by olemagnus**

### CODE REVIEW

**Comment by crswll** [comment]
I believe the path was fine due:

https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.base.conf.js#L34

**Comment by asumaran** [comment]
heh. I noticed this as well and submitted the same fix https://github.com/vuejs-templates/webpack/pull/478 Hope this get merged soon.

**Comment by posva** [comment]
as @asumaran said, this is a duplicate of #478

**Comment by kazupon** [comment]
Thank you so much for the effort. 🙇
Fixed #478

**Pull request closed without merging**
