### PR TITLE
Add Vuex and vue-router as options

### PR DESCRIPTION
**Pull request by nickmessing**
I think we need vuex and vue-router options in a boilerplate. Is here anyone who wants to fix test/docs for this?

P.S. I guess we should show more from vuex, router, test it, document it and make something like webpack-advanced boilerplate for that instead of filling this one.

### CODE REVIEW

**Comment by pksunkara** [comment]
I did make an earlier pull request for this at https://github.com/vuejs-templates/webpack/pull/296#discussion_r82073211 but the maintainers rejected it.

**Comment by nickmessing** [comment]
@pksunkara, It would be awesome if contributors create a repo like webpack-advanced or webpack-complete so we can do vuex/vue-router in there with like lots of options, maybe we should try to convince them it's needed?

**Comment by pksunkara** [comment]
@nickmessing I had given up and started on https://github.com/pksunkara/spoiler

**Comment by nickmessing** [comment]
@pksunkara, hmm, nice, are contributions welcome?

**Comment by pksunkara** [comment]
Definitely 😄

**Comment by chrisvfritz** [comment]
Glad to see a community project providing this!

**Comment by gkatsanos** [comment]
I don't understand what's the use of the "keeping it simple" - having a generator which doesn't have a routing system is a bit pointless right?

**Comment by chrisvfritz** [comment]
@gkatsanos No, it's obviously not "pointless" or no one would use this template. You can see [this discussion](https://github.com/vuejs-templates/webpack/pull/296#discussion_r82073211) for more details on trade-offs we're trying to balance. Please keep criticism polite and constructive.

**Comment by gkatsanos** [comment]
I guess as long as there's a webpack-advanced template, 90% of use cases would be covered :) 
Personally I don't mind doing things manually at this phase as it's a means for learning. But when you're past the 2nd or 3rd project, automation is basics can accelerate/facilitate the work a lot.

My Criticism was maybe a bit sharp, but it was definitely both constructive and polite, unlike some other comments I read which were definitely not constructive.

**Pull request closed without merging**
