### PR TITLE
cleanup build moving common functions to utils

### PR DESCRIPTION
**Pull request by miljan-aleksic**
The changes were tested, the Build process works exactly the same as before with few advantages: the code is cleaner and the build could execute different webpack builds easily (required in some projects).

### CODE REVIEW

**Comment by LinusBorg** [comment]
I like this.

**Comment by miljan-aleksic** [comment]
Why not merge it, then? :)

**Comment by LinusBorg** [comment]
Because I haven't come around to test this locally. And since there are no automated tests for this, I won't merge before I (or someone else) have done that.

**Comment by yyx990803** [comment]
I'm not sure if this is necessary. The build code is only needed in `build.js`, it's not reusable/reused, so I'd rather keep it where it's actually used. Thanks for the PR though!

**Pull request closed without merging**
