### PR TITLE
[WIP]add ts support

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
TS is getting extremely popular,so we can support it~

### CODE REVIEW

**Comment by Toilal** [comment]
It should be an option, as some people don't want to use TypeScript.

**Comment by Aladdin-ADD** [comment]
@Toilal agree~ I will do it later.

**Comment by Toilal** [comment]
For people coming here, I have issues with `.vue` files support when using typescript inside my IDE (IntellijIDEA), so I wrote a fork of this template implementing a TypeScript option, but dropping the vue files in favor of splitted files (js / ts / html / css) => https://github.com/Toilal/vue-webpack-template

**Comment by githubmann** [comment]
any progress?

**Comment by Aladdin-ADD** [comment]
@githubmann sorry for the delay, I have been so busy these days. so if you have time to give an extra hand, that would be great!

**Comment by Aladdin-ADD** [comment]
closing, as there is another PR #797

**Pull request closed without merging**
