### PR TITLE
Integrate the option to add Foundation node package

### PR DESCRIPTION
**Pull request by BillyPurvis**
Foundation is super handy, but I found no clear guide on how to add Foundation's NPM to webpack, or vue too easily. This repo adds that ability, with a prompt to decide if you want it or not. 

Adds 
 - foundation-sites
 - node-sass
 - sass-loader

### CODE REVIEW

**Comment by BillyPurvis** [comment]
Certain build files reference my name as part of testing, if required, I could remove these references.

**Comment by nickmessing** [comment]
@BillyPurvis, the `webpack` tempalte is kept as simple as possible, things like `foundation` are not general needs. Even `vuex` which is a part of `vue` ecosystem is not included so if you want to have a template with `foundation` you should keep it in a separate repository.

**Comment by BillyPurvis** [comment]
@nickmessing A shame, but understandable. Would you prefer me to move the project from the fork to a few repository and continue development?

**Comment by grantcarthew** [comment]
Check out [vue-foundation](https://github.com/hal0gen/vue-foundation)

**Pull request closed without merging**
