### PR TITLE
update book

### PR DESCRIPTION
**Pull request by pin3da**
Some links were fixed here 3225018bc145 but the documentation is still out of date.

### CODE REVIEW

**Comment by LinusBorg** [comment]
I think instead of manually patching the generated HTML, we should update the docs by genrating new files.

/ping @chrisvfritz

**Comment by pin3da** [comment]
@LinusBorg I tried to generate new files but github does not allow me to raise the PR in that way.

**Comment by LinusBorg** [comment]
Yeah our team has to do that.

**Comment by chrisvfritz** [comment]
Just updated!

**Pull request closed without merging**
