### PR TITLE
Add source maps for karma

### PR DESCRIPTION
**Pull request by posva**
Hello,

I just added karma sourcemaps so you can debug easier.

There's no info about how to debug with Phantomjs, I can add it as well of adding how to debug with a real browser (which is much easier) in the readme if you want me to :wink:

### CODE REVIEW

**Comment by yyx990803** [comment]
Thanks! Ran into an issue where it would complain about sourceMap position not found in some cases, tracked down the problem and almost ready to submit a PR to fix it... then found this: https://github.com/karma-runner/karma/issues/1274

Surprisingly it has been there for over a year and was just fixed just 8 days ago...

**Comment by posva** [comment]
That's interesting, I ran into other errors that may be missleading. I'm interested in the code you where running to get those errors. Mind sharing it?

**Comment by yyx990803** [comment]
If you have errors thrown inside a `*.vue` file you will see that warning. (It still works though)

**Comment by posva** [comment]
I see, thanks for the explanation

**Pull request merged**
