### PR TITLE
speed up

### PR DESCRIPTION
**Pull request by MillerRen**
ignore watch node_modules directory

### CODE REVIEW

**Comment by LinusBorg** [comment]
Seems useful! Is the improvement noticable?

I found other issues like this one that actually saw slowdowns: https://github.com/webpack/webpack/issues/979

**Comment by MillerRen** [comment]
847ms -> 256ms in my local machine. Linux has watch files number limit.

**Comment by LinusBorg** [comment]
Alright, I will test this on a project and will report back here.

**Comment by yyx990803** [comment]
I tested on the latest branch with Webpack 2 and other projects using Wepback 2, and it seems there's no difference at all after adding this plugin... but thanks for the PR!

**Pull request closed without merging**
