### PR TITLE
Add standard package for standard lint option

### PR DESCRIPTION
**Pull request by dennisreimann**
This allows for nicer integration with editor plugins (i.e. [VS Code Standard Style](https://marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standardjs).

### CODE REVIEW

**Comment by LinusBorg** [comment]
What exactly does this do? "nicer integration" doesn't say much. I started writing changelogs so it might be helpful to mention what this actually helps with.

**Comment by dennisreimann** [comment]
If you don't have standard installed globally, the VS Code Standard plugin complains about not being able to find the package (if it's not installed as a `devDependency`). 

A question I had in mind before proposing this: Does it make sense to do linting via ESLint in case one uses the `standard` option? To me it feels a bit redundant.

**Comment by LinusBorg** [comment]
Thanks, that's clearer.

Well, this template doesn't assume people are using a spoecific editor or editor-plugin. IF people do, it's their responsibility to decide what do use and how to make it work.

So I would say that I don't think adding the `standard` package makes too much sense, since using both this and eslint would be uncesessary, would you agree?

**Comment by dennisreimann** [comment]
Yeah, that's alright :)

**Pull request closed without merging**
