### PR TITLE
Add coverage for components and js with isparta

### PR DESCRIPTION
**Pull request by posva**
Hi,

I added coverage to js and vue files. I don't know if we really want to have this in the webpack template but it definitely deserves some discussion :smile:
Also I don't know what you think about coverage on components

screen shot 2016-03-04 at 09 41 09

IMO the code should be improved before merging (if it ever gets merged)

### CODE REVIEW

**Comment by yyx990803** [comment]
Yeah, I'm starting to think maybe we need to make some parts of the template optional via CLI prompts.

e.g. do you want eslint? do you want coverage? do you even want tests?

**Comment by posva** [comment]
Yep, having some optional features could be great. We would need to add some way of customizing it through the templates

**Comment by ameesters** [comment]
For acceptance in enterprise/corporate environments have coverage is crucial. I work for a big world-wide company and am currently pushing for Vue, but coverage is very important for us due to audits from 3th parties before using our software.

So i am really excited seeing this happen!

Offtopic: i also asked a question about it on the forum for a demo application in vue: http://forum.vuejs.org/topic/3081/test-coverage-report

**Comment by posva** [comment]
@ameesters I added a comment on the forum just for the record

**Comment by yyx990803** [comment]
Sorry for not getting this merged - I ended up making some big refactoring to the template, and included coverage config in those changes. Really appreciate raising the issue though!

**Comment by posva** [comment]
@yyx990803 Cool! I like the refactoring you did

**Comment by posva** [comment]
It doesn't matter it doesn't get merged ofc :smile:

**Pull request closed without merging**
