### PR TITLE
babel-register use only for e2e tests

### PR DESCRIPTION
**Pull request by PowerfulPony**
Single require here template/test/e2e/nightwatch.conf.js

### CODE REVIEW

**Comment by LinusBorg** [comment]
What would be the advantage of this?

**Comment by PowerfulPony** [comment]
If you do not use e2e, the unused dependency will not be loaded. When studying the project, there is no question of why this dependence is necessary.

**Comment by LinusBorg** [comment]
> there is no question of why this dependence is necessary.

Then maybe I'm stupid. Enlighten me.

**Comment by LinusBorg** [comment]
Fixed the merge conflict created by #1118

**Pull request merged**
