### PR TITLE
Add support for building documentation with VuePress

### PR DESCRIPTION
**Pull request by ghost**
This pull request adds a config.js file for VuePress, the vue.js community's own documentation tool. This file allows you to make a static build using `vuepress build` (once vuepress is installed on the machine with yarn or npm).

### CODE REVIEW

**Comment by ghost** [comment]
CC: @LinusBorg

**Comment by ghost** [comment]
Just for clarification, use vuepress build when you are in the docs directory.

**Comment by ghost** [comment]
@LinusBorg Is there anything I need to add to my pull request?

**Comment by ghost** [comment]
hey @LinusBorg is this still planned to be merged?

**Comment by LinusBorg** [comment]
No. I'm not planning on adding anything to this template.

Vue CLI 3 has been stable for half a year almost. This template won't be developed any further in favor of Vue CLI 3

**Pull request closed without merging**
