### PR TITLE
Updating dependencies

### PR DESCRIPTION
**Pull request by morficus**
Bumping dependencies for the generated project to their latest verions

### CODE REVIEW

**Comment by LinusBorg** [comment]
You added a bunch of major version bumps, which means breaking changes. This should be throughly tested.

**Comment by morficus** [comment]
I'm currently using the bumped version on 2 projects w/o any additional config changes.
But I am open to ways of testing these out.

**Comment by chrisvfritz** [comment]
Thanks @morficus! As @LinusBorg mentioned, since these templates are not very modular or easily testable at the moment, a bunch of major version bumps all at once makes me a little uncomfortable, but I would like to bring this in soon - possibly in an "edge" branch for this repo, where it would be more acceptable if something broke temporarily.

To ease development for the future and when some other work for 2.0 slows down a bit, I'd also like to completely rewrite the templates for 2.0 with a full test suite, so that in the future we'll just be able to say, "Tests pass, looks good, merge" for contributions like this.

**Comment by chrisvfritz** [comment]
Closing for now, as we'll either replace this template with a testable one or update dependencies one-by-one.

**Pull request closed without merging**
