### PR TITLE
automatically check versions of node and npm

### PR DESCRIPTION
**Pull request by chrisvfritz**
@zigomir Review plz? 🙂

### CODE REVIEW

**Comment by zigomir** [comment]
Hi @chrisvfritz! I'll do this tomorrow if it's ok with you? I'm barely from my vacation and had 100 other things to do first.

**Comment by chrisvfritz** [comment]
Oh, no problem! Please take your time - it's definitely not urgent. 😄  And sorry, forgot you were on vacation. 😬

**Comment by chrisvfritz** [comment]
Btw, mostly for GitHub's record, this fixes #325.

**Comment by zigomir** [comment]
Eh, my fault, actually I forgot to mention anywhere (besides job of course) that I'll having one.

First thing that comest to mind is, what about `yarn`? :) But probably we don't need to care about it just yet. 

Another, more important question that comest to my mind: should we move the logic directly to `vue-cli` and inform user after download? I know user can use/install `vue-cli` with different node version, but still, this way all templates could benefit from just adding `engines` part to `package.json`.

Otherwise LGTM (I tried it locally and works fine). If it solves problems I'd merge this and try it out here and maybe later port to `vue-cli`, if or when it turns out to be useful.

**Comment by chrisvfritz** [comment]
Sounds good to me! Thanks for the review. 🙂

**Pull request merged**
