### PR TITLE
Use vue-test for component testing

### PR DESCRIPTION
**Pull request by callumacrae**
I wrote [vue-test](https://github.com/callumacrae/vue-test) because I didn't like that I had to interact with the Vue internals to test my components. It was especially irritating when I wanted to pass in props to the component, because there's no way to just pass in an object (https://github.com/vuejs/vue/issues/2114).

A couple other people have said they'd find it useful, so I figured I'd send a PR to the template :)

I'm actively using the module as part of my job, so it'll be well maintained. That said, feel free to reject this PR if you feel the library is unnecessary or don't want to add a dependency :)

[vue-test]: https://github.com/callumacrae/vue-test

### CODE REVIEW

**Comment by LinusBorg** [comment]
Hey, thanks for this! 

I think we won't merge this yet as we still are not sure what test support lib we want to add - a few different ones for vue were repressed recently, and we want to evaluate all of them before we decide. 

Will report back when we know more, ok?

**Comment by callumacrae** [comment]
Yeah, sure! The most popular one seems to be a copy of my one (even down to `import { mount } from 'module-name';`), but I guess that's what I get for taking six months to release 1.0.0.

**Comment by LinusBorg** [comment]
Closing because we will be using github.com/vuejs/vue-test-utils once they are officially released.

**Comment by lusarz** [comment]
@LinusBorg Would you accept pull request with [vue-test-utils@v1.0.0-beta.28](https://github.com/vuejs/vue-test-utils/releases/tag/v1.0.0-beta.28) configuration if I prepare it ?

I actually have it configured [here](https://github.com/lusarz/vue-test-utils-examples/commit/8d4756de3d3324f0d58f9e44213ccbea99f664c2), so I can easily apply it here.

**Comment by LinusBorg** [comment]
This template is deprecated in favor of vue-cli 3. We will not add any new features or major updates to it.

**Comment by lusarz** [comment]
Okay, I understand. So where I can found source code of analogous template related with vue-cli 3 ?

**Comment by LinusBorg** [comment]
vue-cli 3 does everthing this template does and more out of the box. 

https://cli.vuejs.org

**Pull request closed without merging**
