### PR TITLE
Add npm script for fixing lint errors

### PR DESCRIPTION
**Pull request by sudo-suhas**
Adds an npm script to fix eslint errors/warnings which are auto-fixable.

### CODE REVIEW

**Comment by sudo-suhas** [comment]
If this is approved, I can make a similar PR to vuejs-templates/pwa

**Comment by MaxMilton** [comment]
I like this idea in general but how does it fix into the development workflow, when are devs meant to run this command? Is it something that devs are expected to script into their git commit hook? If so should we also add some documentation for this? Otherwise I suspect people won't use it.

**Comment by nickmessing** [comment]
@MaxMilton, I use that as git commit hook since it fails if there are "unfixable" rules failing. I think it's worth a shot to add it as precommit hook but I don't know if we want to make it a part of `webpack` template. This should be bare minimal webpack template.

**Comment by sudo-suhas** [comment]
TBH, I use the `lint` or `lint:fix` script commands quite rarely. I usually setup pre  commit hooks with `lint-staged`

**Comment by sudo-suhas** [comment]
@LinusBorg Shall I close this?

**Comment by LinusBorg** [comment]
@sudo-suhas I'm not sure about this. I add these to my projects as well, sometimes.

On the other hand, I don't want to add too many scripts to the package.json and blow up the list. it should be quite easy for anyone interested in this option to add it, and I'm not even sure if I want to have people use it that haven't even understood what it does...

**Comment by sudo-suhas** [comment]
I understand @LinusBorg. Closing.

**Pull request closed without merging**
