### PR TITLE
Adding Babel register to Nightwatch conf

### PR DESCRIPTION
**Pull request by ianwalter**
This *one weird trick* allows you to use ES6 syntax with your Nightwatch tests!

### CODE REVIEW

**Comment by chrisvfritz** [comment]
`babel-core/register` is actually near deprecation. From the source:

```js
// TODO: eventually deprecate this console.trace("use the `babel-register` package instead of `babel-core/register`");
module.exports = require("babel-register");
```

This file and the surrounding files also follow the [ferross/standard](https://github.com/feross/standard) style, so no unnecessary semicolons please. 😃

**Comment by ianwalter** [comment]
@chrisvfritz Ok, all set.

**Comment by chrisvfritz** [comment]
@ianwalter Thanks! I know this sounds like a nitpick, but in `package.json`, the `babel-register` dependency should be also be placed in alphabetical order. (It's still functional the way you have it, but people are used to scanning their dependencies list with this in mind.)

**Comment by ianwalter** [comment]
Np, nitpicks welcome.

**Pull request merged**
