### PR TITLE
loader and fallbackLoader are deprecated

### LINKED ISSUE #480: loader and fallbackLoader are deprecated
Running e2e test triggers warnings:
```
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
```

Warning goes away if [build/utils.js](https://github.com/vuejs-templates/webpack/blob/master/template/build/utils.js#L31) is updated replace
```js
      return ExtractTextPlugin.extract({
        loader: sourceLoader,
        fallbackLoader: 'vue-style-loader'
      })

```
with
```js
      return ExtractTextPlugin.extract({
        use: sourceLoader,
        fallback: 'vue-style-loader'
      })

```

### PR DESCRIPTION
**Pull request by limichange**
Fixed #480

### CODE REVIEW

**Comment by amirrustam** [comment]
Can confirm the fix works.

**Comment by limichange** [comment]
@LinusBorg Can you merge this ? many people has this problem.

**Comment by alfeg** [comment]
I have to add one more change - to make webpack 2 happy
```javascript
    function generateLoaders(loaders) {
        var sourceLoader = loaders.map(function (loader) {
            var extraParamChar
            if (/\?/.test(loader)) {
                loader = loader.replace(/\?/, '-loader?')
                extraParamChar = '&'
            } else {
                loader = loader + '-loader'
                extraParamChar = '?'
            }
            return loader + (options.sourceMap ? extraParamChar + 'sourceMap' : '')
        })

        // Extract CSS when that option is specified
        // (which is the case during production build)
        if (options.extract) {
            return ExtractTextPlugin.extract({
                use: sourceLoader,
                fallback: 'vue-style-loader'
            })
        } else {
            return ['vue-style-loader', sourceLoader.join('!')].join('!')
        }
    }
```
use accept arrays, not a string. So I moved `.join('!')` down the road

**Comment by limichange** [comment]
🤔 
https://github.com/webpack-contrib/extract-text-webpack-plugin#extract

**Comment by kazupon** [comment]
Thank you so much for the effort. 🙇
Fixed with #490

**Pull request closed without merging**
